[deploy]
bucket = 'cfn-artifacts-cmd-1001'
region = 'us-east-1'
stack_name = 'CrudddurSyncRole'

[parameters]
GitHubOrg = 'PatrickCmd'
RepositoryName = 'aws-bootcamp-cruddur-2023'
OIDCProviderArn = ''