[deploy]
bucket = 'cfn-artifacts-cmd-1001'
region = 'us-east-1'
stack_name = 'CrdSrvBackendFlask'

[parameters]
EnvFrontendUrl = 'https://cruddurcorecodecmdsystems.website'
EnvBackendUrl = 'https://api.cruddurcorecodecmdsystems.website'
DDBMessageTable = 'CrdDdb-DynamoDBTable-T3EEQ2JWVSKP'
