[deploy]
bucket = 'cfn-artifacts-cmd-1001'
region = 'us-east-1'
stack_name = 'CrudderSrvBackendFlask'

[parameters]
EnvFrontendUrl = 'https://cruddurcorecodecmdsystems.website'
EnvBackendUrl = 'https://api.cruddurcorecodecmdsystems.website'
DDBMessageTable = 'CruddurdDynamoDB-DynamoDBTable-K2QAEWUJWQG8'